// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhbhdwzsiadnindgrinw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoYmhkd3pzaWFkbmluZGdyaW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTU2MjIsImV4cCI6MjA2MDE5MTYyMn0.FCqz6kGfVrwKzNNCC5FzRf9DjlTUjwrqSnxCt0R7VdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);